openapi: 3.0.4
info:
  title: Gravatar Lookup
  description: Gravatar Lookup is a simple tool for looking up Gravatar profiles. It returns the Gravatar profile information of the email address provided.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/gravatarlookup:
    get:
      summary: Lookup Gravatar Profile
      description: Gravatar Lookup is a simple tool for looking up Gravatar profiles. It returns the Gravatar profile information of the email address provided.
      operationId: gravatarlookup
      parameters:
      - name: email
        in: query
        schema:
          type: string
        required: true
        description: The email address to lookup the Gravatar profile of
        example: hello@apiverve.com
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  profileUrl: https://gravatar.com/apiverve
                  thumbnailUrl: https://0.gravatar.com/avatar/08ccd5c0bdd88b0ac13f776a4f7914db
                  photos:
                  - value: https://0.gravatar.com/avatar/08ccd5c0bdd88b0ac13f776a4f7914db
                    type: thumbnail
                  displayName: APIVerve
                  aboutMe: >-
                    APIVerve stands out as a premier source for cloud-based API and Software-as-a-Service (SaaS) solutions catering to developers, startups and products.


                    At APIVerve, we take pride in being a leading provider of cutting-edge cloud-based API and Software-as-a-Service (SaaS) solutions tailored to meet the diverse needs and unlock new possibilities across various industries.
                  currentLocation: United States
                  company: APIVerve
                  contactInfo:
                  - type: contactform
                    value: apiverve.com/contact
                  accounts:
                  - domain: twitter.com
                    display: '@apivervehq'
                    url: https://twitter.com/apivervehq
                    iconUrl: https://gravatar.com/icons/twitter-alt.svg
                    is_hidden: false
                    username: apivervehq
                    verified: true
                    name: Twitter
                    shortname: twitter
                  - domain: github.com
                    display: apivervehq
                    url: https://github.com/apivervehq
                    iconUrl: https://gravatar.com/icons/github.svg
                    is_hidden: true
                    username: apivervehq
                    verified: true
                    name: GitHub
                    shortname: github
                  - domain: calendly.com
                    display: apiverve
                    url: https://calendly.com/apiverve
                    iconUrl: https://gravatar.com/icons/calendly.svg
                    is_hidden: false
                    username: calendly.com
                    verified: true
                    name: Calendly
                    shortname: calendly
                  username: apiverve
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
